# Generated by Django 4.2.6 on 2023-12-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_key_alter_user_is_active_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True, verbose_name='ключ пользователя'),
        ),
    ]
