# Generated by Django 4.2.6 on 2023-11-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_options_material_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Cтатья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
